name: Build and Deploy to Netlify
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js (if needed for build)
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version

      - name: Install dependencies (if needed for build)
        run: npm install # Or yarn install, pnpm install

      - name: Build project (if needed)
        run: npm run build # Or your specific build command, e.g., yarn build, ng build --prod

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./dist"
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
